import { create } from 'zustand';
import { supabase } from '../lib/supabase';
import { registerResettable } from './dataLifecycle';
import { createStaleGuard } from './staleGuard';
import { getDataErrorMessage } from '../utils/getDataErrorMessage';
import type { Customer } from '../types';

type Status = 'idle' | 'loading' | 'loaded' | 'error';

export interface AddCustomerInput {
  name: string;
  email: string;
  company?: string;
  notes?: string;
}

interface CustomerState {
  customers: Customer[];
  status: Status;
  error: string | null;
  loadForUser: (userId: string) => Promise<void>;
  addCustomer: (userId: string, input: AddCustomerInput) => Promise<Customer>;
  updateCustomer: (userId: string, id: string, patch: Partial<Omit<Customer, 'id'>>) => Promise<void>;
  getCustomerById: (id: string) => Customer | undefined;
  // Both call server-side RPCs (migration 0014) -- the token itself is
  // always generated by gen_random_uuid() in Postgres, never client-side.
  ensurePortalToken: (userId: string, id: string) => Promise<string>;
  regeneratePortalToken: (userId: string, id: string) => Promise<string>;
  reset: () => void;
}

const AVATAR_COLORS: Customer['avatarColor'][] = ['mint', 'lavender', 'blue', 'red'];

const guard = createStaleGuard();

function mapRow(row: {
  id: string;
  name: string;
  email: string;
  avatar_color: Customer['avatarColor'];
  avatar_url: string | null;
  image_type: Customer['imageType'] | null;
  company: string | null;
  notes: string | null;
  portal_token?: string | null;
  portal_token_created_at?: string | null;
}): Customer {
  return {
    id: row.id,
    name: row.name,
    email: row.email,
    avatarColor: row.avatar_color,
    avatarUrl: row.avatar_url ?? undefined,
    imageType: row.image_type ?? undefined,
    company: row.company ?? undefined,
    notes: row.notes ?? undefined,
    portalToken: row.portal_token ?? undefined,
    portalTokenCreatedAt: row.portal_token_created_at ?? undefined,
  };
}

export const useCustomerStore = create<CustomerState>()((set, get) => ({
  customers: [],
  status: 'idle',
  error: null,

  loadForUser: async (userId) => {
    const token = guard.next();
    set({ status: 'loading', error: null });
    try {
      const { data, error } = await supabase
        .from('customers')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });
      if (error) throw error;
      if (!guard.isCurrent(token)) return;
      set({ customers: (data ?? []).map(mapRow), status: 'loaded' });
    } catch (error) {
      if (!guard.isCurrent(token)) return;
      set({ status: 'error', error: getDataErrorMessage(error, 'customers') });
    }
  },

  addCustomer: async (userId, input) => {
    guard.next(); // invalidate any in-flight load — this optimistic write must survive it
    const avatarColor = AVATAR_COLORS[get().customers.length % AVATAR_COLORS.length];
    const { data, error } = await supabase
      .from('customers')
      .insert({
        user_id: userId,
        name: input.name,
        email: input.email,
        company: input.company ?? null,
        notes: input.notes ?? null,
        avatar_color: avatarColor,
      })
      .select('*')
      .single();
    if (error) {
      set({ error: getDataErrorMessage(error, 'customers', 'save') });
      throw error;
    }
    const customer = mapRow(data);
    set((state) => ({ customers: [customer, ...state.customers] }));

    // Phase 6C: logged after the customer row is already durably created
    // above -- not optimistic, the underlying fact already happened. RLS
    // (notifications_insert_customer_added) only ever permits this exact
    // type, for the caller's own account, so this can't be used to write
    // any other notification. Best-effort, fire-and-forget: a failure here
    // must never surface as if adding the customer itself failed, so this
    // is deliberately not awaited by addCustomer's own return.
    void (async () => {
      const { error: notifyError } = await supabase.from('notifications').insert({
        user_id: userId,
        type: 'customer_added',
        title: 'Customer added',
        message: `${customer.name} was added to your customers.`,
        entity_type: 'customer',
        entity_id: customer.id,
      });
      if (notifyError) console.warn('customerStore: failed to log customer_added notification', notifyError);
    })();

    return customer;
  },

  updateCustomer: async (userId, id, patch) => {
    guard.next();
    const dbPatch: Record<string, unknown> = {};
    if ('name' in patch) dbPatch.name = patch.name;
    if ('email' in patch) dbPatch.email = patch.email;
    if ('company' in patch) dbPatch.company = patch.company ?? null;
    if ('notes' in patch) dbPatch.notes = patch.notes ?? null;
    if ('avatarUrl' in patch) dbPatch.avatar_url = patch.avatarUrl ?? null;
    if ('imageType' in patch) dbPatch.image_type = patch.imageType ?? null;

    const { error } = await supabase.from('customers').update(dbPatch).eq('id', id).eq('user_id', userId);
    if (error) {
      set({ error: getDataErrorMessage(error, 'customers', 'save') });
      throw error;
    }
    set((state) => ({ customers: state.customers.map((c) => (c.id === id ? { ...c, ...patch } : c)) }));
  },

  getCustomerById: (id) => get().customers.find((c) => c.id === id),

  ensurePortalToken: async (userId, id) => {
    const { data, error } = await supabase.rpc('ensure_customer_portal_token', { p_customer_id: id });
    if (error) {
      set({ error: getDataErrorMessage(error, 'customers', 'save') });
      throw error;
    }
    const token = data as string;
    set((state) => ({
      customers: state.customers.map((c) => (c.id === id ? { ...c, portalToken: token } : c)),
    }));
    return token;
  },

  regeneratePortalToken: async (userId, id) => {
    const { data, error } = await supabase.rpc('regenerate_customer_portal_token', { p_customer_id: id });
    if (error) {
      set({ error: getDataErrorMessage(error, 'customers', 'save') });
      throw error;
    }
    const token = data as string;
    set((state) => ({
      customers: state.customers.map((c) => (c.id === id ? { ...c, portalToken: token } : c)),
    }));
    return token;
  },

  reset: () => {
    guard.next();
    set({ customers: [], status: 'idle', error: null });
  },
}));

registerResettable(() => useCustomerStore.getState().reset());
