import { View, Text, ScrollView, Switch, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { useTheme } from '../../../src/theme/useTheme';
import { AppHeader } from '../../../src/components/AppHeader';
import { TAB_BAR_CONTENT_HEIGHT } from '../../../src/components/BottomNavigation';
import { ThemeAwareCard } from '../../../src/components/ThemeAwareCard';
import { useNotificationStore } from '../../../src/store/notificationStore';
import type { NotificationPreferences } from '../../../src/types';

// Same 5 categories as the Notifications screen's own filter (spec: keep
// this minimal) -- turning one off hides that category from your feed and
// unread count. It does not stop the underlying business event itself from
// being recorded (e.g. a payment is still verified and credited exactly
// the same either way) -- this only controls what you SEE.
const TOGGLES: { key: keyof NotificationPreferences; label: string; description: string }[] = [
  { key: 'payments', label: 'Payments', description: 'Payments received, including partial payments.' },
  { key: 'requests', label: 'Request Updates', description: 'A request being viewed or expiring unpaid.' },
  { key: 'reminders', label: 'Reminders', description: 'Reminders sent to customers, and any that fail to send.' },
  { key: 'recurring', label: 'Recurring Activity', description: 'A new request generated by a recurring plan.' },
  { key: 'customers', label: 'Customer Activity', description: 'A new customer added to your account.' },
];

export default function NotificationsScreen() {
  const { colors, spacing, typography } = useTheme();
  const preferences = useNotificationStore((state) => state.preferences);
  const updatePreferences = useNotificationStore((state) => state.updatePreferences);

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }} edges={['top', 'bottom']}>
      <AppHeader title="Notifications" onBackPress={() => router.back()} />
      <ScrollView contentContainerStyle={{ padding: spacing.xl, paddingBottom: TAB_BAR_CONTENT_HEIGHT + spacing.xl }}>
        <ThemeAwareCard style={{ paddingVertical: 0 }}>
          {TOGGLES.map((toggle, index) => (
            <View
              key={toggle.key}
              style={[
                styles.row,
                { paddingVertical: spacing.md, borderTopWidth: index === 0 ? 0 : 1, borderTopColor: colors.border },
              ]}
            >
              <View style={{ flex: 1, marginRight: spacing.md }}>
                <Text style={[typography.body, { color: colors.textPrimary }]}>{toggle.label}</Text>
                <Text style={[typography.caption, { color: colors.textMuted, marginTop: spacing.xs / 2 }]}>
                  {toggle.description}
                </Text>
              </View>
              <Switch
                value={preferences[toggle.key]}
                onValueChange={(value) => updatePreferences({ [toggle.key]: value })}
                trackColor={{ true: colors.primaryAction, false: colors.border }}
                thumbColor={colors.surface}
                accessibilityLabel={toggle.label}
              />
            </View>
          ))}
        </ThemeAwareCard>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center' },
});
