// '.ts' extension required -- this file is reachable from the
// verify-payment Edge Function's Deno dependency graph (via
// paymentAccounting.ts), see paymentAccounting.ts's own comment.
import type { AssetSymbol } from '../config/assets.ts';

export type PaymentRequestStatus = 'pending' | 'confirming' | 'paid' | 'expired' | 'cancelled';

export type ExpiryOption = '1h' | '24h' | '7d' | 'never';

export interface PaymentRequest {
  id: string;
  paymentCode: string;
  amount: number;
  // Phase 7: the asset this request is actually denominated in --
  // 'USDC' | 'EURC' (src/config/assets.ts is the single source of truth).
  // Permanent once created; changing the business's default currency
  // (paymentDefaultsStore) never rewrites an existing request's currency.
  currency: AssetSymbol;
  network: 'Solana';
  description?: string;
  customerId?: string;
  expiryOption: ExpiryOption;
  expiresAt: string | null;
  // Separate from expiresAt -- when the merchant expects to be paid by (a
  // reminder-scheduling concern), not when the checkout link itself stops
  // accepting payment (a Solana Pay/QR concern). Optional (unlike
  // expiresAt, every existing PaymentRequest fixture across the test
  // suite would otherwise need updating for a field they don't exercise)
  // -- undefined/null both mean "no due date set", reminders can't be
  // scheduled without one.
  dueAt?: string | null;
  note?: string;
  status: PaymentRequestStatus;
  createdAt: string;
  /** @deprecated Not a working public URL — see getPublicPaymentUrl(publicToken) instead. */
  paymentLink: string;
  /** Opaque public bearer token — the only safe identifier for a shareable checkout link. */
  publicToken: string;
  /** Solana Pay reference public key (no matching secret key exists anywhere) — null for requests created before Phase 3C. */
  solanaReference: string | null;
  // Phase 4C: when false (the default, and every request created before
  // this phase), a request behaves exactly as it always has -- one
  // transaction for the full amount. When true, the request may accumulate
  // multiple verified transactions; "Partially Paid" is never a stored
  // status value, only ever derived from summing real transactions (see
  // src/utils/paymentAccounting.ts) against `amount`.
  allowPartialPayments?: boolean;
  depositType?: 'fixed' | 'percentage';
  depositValue?: number;
  // Set only for a request generated by a recurring plan -- see
  // src/types/recurring.ts. recurringOccurrenceNumber is the plan's own
  // idempotency key (never re-derived client-side).
  recurringPlanId?: string;
  recurringOccurrenceNumber?: number;
  // Archived != deleted (spec): a real timestamp (not a boolean) so WHEN a
  // request was archived is preserved, not just THAT it was. Optional
  // (like dueAt above) rather than a required `string | null` -- every
  // existing PaymentRequest fixture across the test suite would otherwise
  // need updating for a field they don't exercise. undefined/null both
  // mean "never archived" -- every request that existed before this field
  // was added, and every newly created one. Status, payment history, and
  // every identifier are completely unaffected by this field; it only
  // controls default list visibility.
  archivedAt?: string | null;
}

export interface Transaction {
  id: string;
  requestId: string;
  amount: number;
  // Always copied from the parent request's own currency at verification
  // time (see complete_verified_payment) -- a transaction can never be a
  // different asset than the request it settles.
  currency: AssetSymbol;
  network: 'Solana';
  fromCustomerId: string;
  txHash: string;
  paidAt: string;
}

export type RequestEventType =
  | 'created'
  | 'shared'
  | 'payment_detected'
  | 'payment_confirmed'
  | 'payment_failed'
  | 'reminder_sent'
  | 'reminder_scheduled'
  | 'reminder_failed'
  | 'reminder_cancelled'
  | 'cancelled'
  | 'expired';

export interface RequestEvent {
  id: string;
  requestId: string;
  type: RequestEventType;
  occurredAt: string;
}
